myblog/main/urls.py
from django.urls import path

from .views import index, by_category, detail

app_name = 'main'

urlpatterns = [
    path('<int:category_pk>/<int:pk>/', detail, name='detail'),
    path('<int:pk>/', by_category, name='by_category'),
    path('', index, name='index')
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('captcha/', include('captcha.urls')),
    path('', include('main.urls')),

]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/main/models.py
# Third-party imports
from precise_bbcode.fields import BBCodeTextField

# Django imports
from django.db import models
from django.contrib.auth.models import AbstractUser


# Models
class AdvancedUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True, verbose_name='Активация пройдена?')
    send_messages = models.BooleanField(default=True, verbose_name='Отправлять оповещения на почту?')

    class Meta(AbstractUser.Meta):
        pass


class PostCategory(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название категории')
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = 'Категории'
        verbose_name = 'Категория'

    def __str__(self):
        return self.name


class Post(models.Model):
    category = models.ForeignKey(PostCategory, on_delete=models.PROTECT)
    author = models.ForeignKey(AdvancedUser, on_delete=models.CASCADE, verbose_name='Автор')
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.SlugField(unique=True)
    content = BBCodeTextField(null=True, blank=True, verbose_name='Текст поста')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_active = models.BooleanField(default=True, verbose_name='Выводить на сайте?')

    class Meta:
        verbose_name_plural = 'Посты'
        verbose_name = 'Пост'

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Пост')
    author = models.CharField(max_length=30, verbose_name='Автор')
    content = models.TextField(verbose_name='Содержание')
    is_active = models.BooleanField(default=True, db_index=True, verbose_name='Выводить на экран?')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликован')

    class Meta:
        verbose_name_plural = 'Комментарии'
        verbose_name = 'Комментарий'
        ordering = ['-created_at']

myblog/main/forms.py
from captcha.fields import CaptchaField

from django import forms

from .models import Comment


class SearchForm(forms.Form):
    keyword = forms.CharField(required=False, max_length=20, label='')


class UserCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('is_active',)
        widgets = {'post': forms.HiddenInput}


class GuestCommentForm(forms.ModelForm):
    captcha = CaptchaField(label='Введите текст с картинки', error_messages={'invalid': 'Неправильный текст'})

    class Meta:
        model = Comment
        exclude = ('is_active',)
        widgets = {'post': forms.HiddenInput}

myblog/main/views.py
from django.shortcuts import render, get_object_or_404
from django.core.signing import BadSignature
from django.core.paginator import Paginator
from django.contrib import messages
from django.db.models import Q

from .utilities import signer
from .forms import SearchForm, GuestCommentForm, UserCommentForm
from .models import AdvancedUser, Post, PostCategory, Comment


# My views
def user_activation(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'email/bad_signature.html')
    user = get_object_or_404(AdvancedUser, username=username)
    if user.is_activated:
        template = 'registration/user_is_activated'
    else:
        template = 'registration/activation_done.html'
        user.is_activate = True
        user.is_activated = True
        user.save()
    return render(request, template)


def get_search_result(request, posts):
    """Возвращает страницу с постами и форму поиска"""
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        posts = posts.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(posts, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    return page, form


def index(request):
    category = PostCategory.objects.all()
    posts = Post.objects.filter(is_active=True)
    page, form = get_search_result(request, posts)
    context = {'category': category, 'page': page, 'posts': page.object_list, 'form': form}
    return render(request, 'main/index.html', context)


def by_category(request, pk):
    category = get_object_or_404(PostCategory, pk=pk)
    posts = Post.objects.filter(is_active=True, category=pk)
    page, form = get_search_result(request, posts)
    context = {'category': category, 'page': page, 'posts': page.object_list, 'form': form}
    return render(request, 'main/by_category.html', context)


def detail(request, category_pk, pk):
    post = Post.objects.get(pk=pk)
    comments = Comment.objects.filter(post=pk, is_active=True)
    initial = {'post': post.pk}
    if request.user.is_authenticated:
        initial['author'] = request.user.username
        form_class = UserCommentForm
    else:
        form_class = GuestCommentForm
    form = form_class(initial=initial)
    if request.method == 'POST':
        c_form = form_class(request.POST)
        if c_form.is_valid():
            c_form.save()
            messages.add_message(request, messages.SUCCESS, 'Комментарий добавлен')
        else:
            form = c_form
            messages.add_message(request, messages.WARNING, 'Комментарий не добавлен')
    context = {'post': post, 'comments': comments, 'form': form}
    return render(request, 'main/detail.html', context)

myblog/main/templates/layout/basic.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}Главная{% endblock %} - Блог</title>
        {% bootstrap_css %}
        <link rel="stylesheet" type="text/css"
        href="{% static 'main/style.css' %}">
        {% bootstrap_javascript jquery='slim' %}
    </head>
    <body class="container-fluid">
        <header class="mb-4">
            <h1 class="display-1 text-center">Мой блог</h1>
        </header>
        <div class="row">
            <ul class="col nav justify-content-end border">
                <li class="nav-item">
                    <form class="col-md-auto form-inline">
                        {% bootstrap_form form show_label=False %}
                        {% bootstrap_button content='Искать' button_type='submit' %}
                    </form>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown"
                    href="#" role="button" aria-haspopup="true"
                    aria-expanded="false">Профиль</a>
                    <div class="dropdown-menu">
                    </div>
                </li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'main:login' %}">Вход</a></li>
                {% endif %}
            </ul>
        </div>
        <div class="row">
            <nav class="col-md-auto nav flex-column border">
                <a class="nav-link root"
                href="{% url 'main:index' %}">Главная</a>
                {% for categ in category %}
                <a class="nav-link" href="{% url 'main:by_category' pk=categ.pk %}">
                {{ categ.name }}</a>
                {% endfor %}
            </nav>
            <section class="col border py-2">
                {% bootstrap_messages %}
                {% block content %}
                {% endblock %}
            </section>
            <nav class="col-sm-1"></nav>
        </div>
        <footer class="mt-3">
            <p class="text-right font-italic">&copy; читатели.</p>
        </footer>
    </body>
</html>

myblog/main/templates/main/by_category.html
{% extends "layout/basic.html" %}

{% load static %}
{% load bootstrap4 %}

{% block title %}{{ category }}{% endblock %}

{% block content %}
<h2 class="mb-2">{{ category }}</h2>

{% if posts %}
<ul class="list-unstyled">
    {% for post in posts %}
    <li class="media my-5 p-3 border">
        {% url 'main:detail' category_pk=post.pk pk=post.pk as url %}
        <div class="media-body">
          <h3><a href="{{ url }}{{ all }}">
          {{ post.title }}</a></h3>
          <div>{{ post.content }}</div>
        </div>
    </li>
    {% endfor %}
</ul>
{% bootstrap_pagination page url=keyword %}
{% endif %}
{% endblock %}

myblog/main/templates/main/index.html
{% extends "layout/basic.html" %}

{% load static %}

{% block content %}
<h2>Последние 10 объявлений</h2>
{% if posts %}
<ul class="list-unstyled">
    {% for post in posts %}
    <li class="media my-5 p-3 border">
        {% url 'main:detail' category_pk=post.category.pk pk=post.pk as url %}
        <div class="media-body">
          <h3><a href="{{ url }}{{ all }}">
          {{ post.title }}</a></h3>
          <div>{{ post.content }}</div>
          <p class="text-right font-italic">{{ bb.created_time }}</p>
        </div>
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}